import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "../../globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-ibm-plex-sans',
  subsets: ["latin"]
})

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-ibm-plex-mono',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body
      className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}
    >
      <div className="items-center justify-center min-h-screen bg-gray-100">
        {children}
      </div>
    </body>
  </html>
  );
}
