import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const ibmPlexSans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-ibm-plex-sans',
  subsets: ["latin"]
})

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: '--font-ibm-plex-mono',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body
      className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}
    >
      <div className="">
        <div className="flex h-screen">
          <div className="w-1/2 relative">
            <Image src={"/icons/login.svg"} alt="Login Image" fill className="object-cover" />
          </div>
          <div className="w-1/2 flex flex-col items-center justify-center min-h-screen bg-gray-100 px-4">
            <div className="flex my-4">
              <Image src="/icons/logo 1.svg" alt="uhs" width={50} height={50} className="mr-2" />
              <h1 className="text-3xl font-bold text-gray-900 mt-1.5">Urban Services</h1>
            </div>
            {children}
          </div>
        </div>
      </div>
    </body>
  </html>
  );
}
